version: '3.8'
services:
  cache1:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - CACHE_PEERS=cache1:8080,cache2:8081,cache3:8082
  cache2:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - CACHE_PEERS=cache1:8080,cache2:8081,cache3:8082
  cache3:
    build: .
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - CACHE_PEERS=cache1:8080,cache2:8081,cache3:8082 